### ISSUE TITLE
可用性：Hex viewer 给 label 加 border

### ISSUE THREAD

**Issue by jixunmoe** [parakeet-rs/docs#6]
```css
.hexEditorHeader {
    border-bottom: 1px solid #333;
    padding-right: 3.5em;
    box-sizing: content-box;
}

.offsetLabel {
    border-right: 1px solid #333;
    margin-right: -1px;
}
```
